# Generated by Django 2.2.5 on 2019-09-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionlevel',
            name='level',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
