# Generated by Django 2.2.5 on 2019-09-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0003_auto_20190907_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='sagurausers',
            name='national_id',
            field=models.CharField(default=123456789, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
