# Generated by Django 2.2.5 on 2019-09-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0004_sagurausers_national_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vegetables',
        ),
        migrations.AddField(
            model_name='fruits',
            name='crop_type',
            field=models.CharField(choices=[('VEGETABLES', 'VEGETABLES'), ('FRUITS', 'FRUITS')], default='FRUITS', max_length=20),
        ),
        migrations.AddField(
            model_name='fruits',
            name='land_preparation',
            field=models.CharField(default='testing', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fruits',
            name='maturity_process',
            field=models.CharField(default='testing', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fruits',
            name='prefered_climate',
            field=models.CharField(default='testing', max_length=1000),
            preserve_default=False,
        ),
    ]
