# Generated by Django 2.2.5 on 2019-09-10 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0005_auto_20190910_1139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fruits',
            new_name='Crops',
        ),
        migrations.AlterModelOptions(
            name='crops',
            options={'verbose_name_plural': 'Fruits & Vegetables'},
        ),
    ]
