# Generated by Django 2.2.5 on 2019-09-12 10:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0007_auto_20190911_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crops',
            options={'verbose_name_plural': 'Crops'},
        ),
        migrations.AlterField(
            model_name='sessionlevel',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=30)),
                ('crop_quanity', models.CharField(max_length=30)),
                ('crop_price', models.CharField(max_length=30)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ussd.SaguraUsers')),
            ],
            options={
                'verbose_name_plural': 'Harvest for Sale',
            },
        ),
    ]
