# Generated by Django 2.2.5 on 2019-09-12 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0008_auto_20190912_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harvest',
            old_name='crop_quanity',
            new_name='crop_quantity',
        ),
    ]
