# Generated by Django 2.2.5 on 2019-09-12 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0009_auto_20190912_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sagurausers',
            name='registered_data',
        ),
        migrations.AddField(
            model_name='harvest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sagurausers',
            name='registered_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
