# Generated by Django 2.2.5 on 2019-09-12 14:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0010_auto_20190912_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ussd.SaguraUsers')),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ussd.Harvest')),
            ],
            options={
                'verbose_name_plural': "Buyer's Orders",
            },
        ),
    ]
